name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 120
    env:
      arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          make deps

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/supabase
          tags: |
            type=sha,format=short,prefix=,suffix=-${{ env.arch }}

      - uses: docker/setup-buildx-action@v2
        with:
          driver: ${{ matrix.arch == 'arm64' && 'docker' || 'docker-container' }}
          driver-opts: ${{ matrix.arch == 'arm64' && 'image=moby/buildkit:master\nnetwork=host' || '' }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ env.arch }}
          cache-from: ${{ matrix.arch == 'arm64' && ' ' || 'type=gha' }}
          cache-to: ${{ matrix.arch == 'arm64' && ' ' || 'type=gha,mode=max' }}
          no-cache: ${{ matrix.arch == 'arm64' }}
          build-args: |
            DEBIAN_VERSION=bullseye-20241202-slim

      - name: Save Digest to File
        run: |
          mkdir -p image-digests
          echo "${{ steps.build.outputs.digest }}" > image-digests/${{ matrix.arch }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: image-digests-${{ matrix.arch }}
          path: image-digests/*.txt


  merge-manifest:
    needs: build
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4

      - run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo "SHORT_SHA=${{ env.SHORT_SHA }}"

      - uses: actions/download-artifact@v4
        with:
          name: image-digests-amd64  # <-- Unique artifact name
          path: ./image-digests

      - uses: actions/download-artifact@v4
        with:
          name: image-digests-arm64  # <-- Unique artifact name
          path: ./image-digests

      - name: Read Digests
        id: read-digests
        run: |
          AMD_DIGEST=$(cat ./image-digests/amd64.txt)
          ARM_DIGEST=$(cat ./image-digests/arm64.txt)
          echo "AMD_DIGEST=$AMD_DIGEST" >> $GITHUB_ENV
          echo "ARM_DIGEST=$ARM_DIGEST" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Multi-Arch Manifests for Versioned Output
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/supabase:${{ env.SHORT_SHA }} \
          ghcr.io/${{ github.repository_owner }}/supabase@${{ env.AMD_DIGEST }} \
          ghcr.io/${{ github.repository_owner }}/supabase@${{ env.ARM_DIGEST }}

#      - uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PAT }}
#
#      - name: mirror
#        uses: akhilerm/tag-push-action@v2.0.0
#        with:
#          src: ghcr.io/${{ github.repository_owner }}/supabase:${{ env.SHORT_SHA }}
#          dst: |
#            docker.io/${{ github.repository_owner }}/supabase:${{ env.SHORT_SHA }}