name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
        include:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 120
    env:
      arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          make build

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/supabase
          tags: |
            type=sha,format=short,prefix=,suffix=-${{ env.arch }}

      - uses: docker/setup-buildx-action@v2
        with:
          driver: ${{ matrix.arch == 'arm64' && 'docker' || 'docker-container' }}
          driver-opts: ${{ matrix.arch == 'arm64' && 'image=moby/buildkit:master\nnetwork=host' || '' }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/supabase:${{ inputs.version }}_${{ env.arch }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ env.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DEBIAN_VERSION=bullseye-20241202-slim

      - id: one
        run: |
          echo "${{ steps.build.outputs.digest }}" >> outputs/${{ matrix.arch }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/*.txt


  print-digests:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Print Image Digests
        run: |
          echo "AMD64 Image Digest: ${{ needs.build.outputs.image_digest_amd64 }}"
          echo "ARM64 Image Digest: ${{ needs.build.outputs.image_digest_arm64 }}"