name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: sudo apt-get -y install binutils
      - run: sudo apt-get -y install fakeroot

      - name: create version number
        shell: bash
        run: echo "VERSION=v$(date +'%Y%m%d.%H%M%S')" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - name: login to registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - run: |
          make deps

      - uses: docker/setup-buildx-action@v3

      - name: build and push Docker image
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max